# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI - Build server and webapp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.19.2
      uses: actions/setup-node@v3
      with:
        node-version: '14.19.2'
        # cache: 'npm'
    
    - name: Build server
      run: |
        pwd
        cd server
        npm ci
        npm run build
    
    - name: Build webapp
      run: |
        pwd
        cd webapp
        npm ci
        npm run build
    
    - name: Print result
      run: |
        pwd
        ls -lah server/dist
        ls -lah webapp/dist
    
    - name: Deploying server
      run: |
        pwd
        mkdir -p server/public
        mv webapp/dist/{.*,*} server/public/ || true
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m 'github-actions deploy'
        git push -f origin `git subtree split --prefix=server master`:built-server
